import { jsPDF } from "jspdf";
import { Ancestor } from "../types";
import { calculateStats } from "../utils/genealogy";

interface ReportImages {
  tree?: string;
  three?: string;
}

export const generateFamilyReport = (ancestors: Ancestor[], images?: ReportImages) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  let cursorY = margin;

  // --- Helpers ---
  const addTitle = (text: string, y: number) => {
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text(text, pageWidth / 2, y, { align: "center" });
    doc.setFont("helvetica", "normal");
  };

  const addHeading = (text: string) => {
    checkPageBreak(15);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(text, margin, cursorY);
    cursorY += 10;
    doc.setFont("helvetica", "normal");
  };

  const addText = (text: string, fontSize = 12, isBold = false) => {
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", isBold ? "bold" : "normal");
    
    // Text wrapping
    const textLines = doc.splitTextToSize(text, pageWidth - margin * 2);
    const textHeight = textLines.length * (fontSize * 0.5); // Approximate height

    checkPageBreak(textHeight);
    doc.text(textLines, margin, cursorY);
    cursorY += textHeight + 2; // Line spacing
  };

  const checkPageBreak = (heightNeeded: number) => {
    if (cursorY + heightNeeded > pageHeight - margin) {
      doc.addPage();
      cursorY = margin;
    }
  };

  const drawDivider = () => {
    checkPageBreak(10);
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, cursorY, pageWidth - margin, cursorY);
    cursorY += 10;
  };

  // --- COVER PAGE ---
  doc.setFillColor(30, 41, 59); // Slate-850
  doc.rect(0, 0, pageWidth, pageHeight, "F");
  
  doc.setTextColor(255, 255, 255);
  addTitle("Family History Report", pageHeight / 3);
  
  doc.setFontSize(14);
  doc.text(`Generated by AncestryAI`, pageWidth / 2, pageHeight / 3 + 20, { align: "center" });
  doc.text(new Date().toLocaleDateString(), pageWidth / 2, pageHeight / 3 + 30, { align: "center" });
  
  doc.addPage();
  doc.setTextColor(0, 0, 0); // Reset text color

  // --- SCREENSHOTS PAGES ---
  if (images?.tree) {
    addHeading("Tree Visualization");
    try {
        const props = doc.getImageProperties(images.tree);
        const pdfWidth = pageWidth - (margin * 2);
        const pdfHeight = (props.height * pdfWidth) / props.width;
        
        // Ensure it fits on page
        const availableHeight = pageHeight - cursorY - margin;
        let finalHeight = pdfHeight;
        let finalWidth = pdfWidth;

        if (pdfHeight > availableHeight) {
             finalHeight = availableHeight;
             finalWidth = (props.width * finalHeight) / props.height;
        }

        doc.addImage(images.tree, 'PNG', margin, cursorY, finalWidth, finalHeight);
        cursorY += finalHeight + 10;
    } catch (e) {
        console.error("Failed to add tree image", e);
        addText("(Image capture failed)");
    }
    doc.addPage();
    cursorY = margin;
  }

  if (images?.three) {
    addHeading("3D World View");
    try {
        const props = doc.getImageProperties(images.three);
        const pdfWidth = pageWidth - (margin * 2);
        const pdfHeight = (props.height * pdfWidth) / props.width;

         // Ensure it fits on page
        const availableHeight = pageHeight - cursorY - margin;
        let finalHeight = pdfHeight;
        let finalWidth = pdfWidth;

        if (pdfHeight > availableHeight) {
             finalHeight = availableHeight;
             finalWidth = (props.width * finalHeight) / props.height;
        }

        doc.addImage(images.three, 'PNG', margin, cursorY, finalWidth, finalHeight);
        cursorY += finalHeight + 10;
    } catch (e) {
        console.error("Failed to add 3D image", e);
        addText("(3D Image capture failed or view was closed)");
    }
    doc.addPage();
    cursorY = margin;
  }

  // --- STATISTICS PAGE ---
  const stats = calculateStats(ancestors);
  
  addHeading("Family Overview");
  
  addText(`Total Family Members: ${stats.total}`);
  addText(`Average Lifespan: ${stats.avgLifespan} years`);
  addText(`Gender Distribution: ${stats.male} Males, ${stats.female} Females, ${stats.unknown} Unknown`);
  
  cursorY += 10;
  addText("This report contains detailed records of all known ancestors, sorted chronologically by birth year.", 11, false);

  drawDivider();

  // --- RECORDS LOOP ---
  // Sort by birth year
  const sortedAncestors = [...ancestors].sort((a, b) => (a.birthYear || 9999) - (b.birthYear || 9999));

  sortedAncestors.forEach((person, index) => {
    // Force page break for every 2-3 records depending on content, or just check space
    checkPageBreak(60); 

    // Name & Dates header
    doc.setFillColor(241, 245, 249); // Slate-100
    doc.rect(margin, cursorY - 5, pageWidth - (margin * 2), 14, "F");
    
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(person.name, margin + 2, cursorY + 4);
    
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text(`${person.birthYear || '?'} - ${person.deathYear || 'Present'}`, pageWidth - margin - 5, cursorY + 4, { align: "right" });
    
    cursorY += 15;

    // Details
    const father = ancestors.find(a => a.id === person.fatherId);
    const mother = ancestors.find(a => a.id === person.motherId);
    
    addText(`Gender: ${person.gender}`, 10);
    addText(`Father: ${father ? father.name : 'Unknown'}`, 10);
    addText(`Mother: ${mother ? mother.name : 'Unknown'}`, 10);
    
    if (person.country) {
        addText(`Country: ${person.country}`, 10);
    }
    
    if (person.notes) {
      cursorY += 3;
      addText("Biography / Notes:", 10, true);
      addText(person.notes, 10);
    }

    cursorY += 10; // Space between records
  });

  // --- FOOTER ---
  const pageCount = doc.internal.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
     doc.setPage(i);
     doc.setFontSize(8);
     doc.setTextColor(150);
     if (i > 1) { // Skip cover
         doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 10, { align: "right" });
     }
  }

  doc.save("AncestryAI_Full_Report.pdf");
};